var t = {
  parentCode: [
    {
      value: 'clock.menu',
      name: '巡检管理',
      label: '巡检管理',
      pinyin: '巡检管理xunjianguanli',
      children: [
        { value: 'clockclockinspection.menu', name: '巡检记录', label: '巡检记录', pinyin: '巡检记录xunjianjilu', children: null, disabled: false },
        { value: 'clockfeedback.menu', name: '反馈列表', label: '反馈列表', pinyin: '反馈列表fankuiliebiao', children: null, disabled: false },
      ],
      disabled: false,
    },
    {
      value: 'comments.menu',
      name: '合作公司管理',
      label: '合作公司管理',
      pinyin: '合作公司管理hezuogongsiguanli',
      children: [
        { value: 'comment.menu', name: '评论记录', label: '评论记录', pinyin: '评论记录pinglunjilu', children: null, disabled: false },
        { value: 'commentoption.menu', name: '选项管理', label: '选项管理', pinyin: '选项管理xuanxiangguanli', children: null, disabled: false },
        { value: 'company.menu', name: '合作公司', label: '合作公司', pinyin: '合作公司hezuogongsi', children: null, disabled: false },
      ],
      disabled: false,
    },
    {
      value: 'content.menu',
      name: '内容管理',
      label: '内容管理',
      pinyin: '内容管理neirongguanli',
      children: [
        { value: 'catalog.menu', name: '目录', label: '目录', pinyin: '目录mulu', children: null, disabled: false },
        { value: 'contentposts.menu', name: '文章', label: '文章', pinyin: '文章wenzhang', children: null, disabled: false },
      ],
      disabled: false,
    },
    {
      value: 'project.menu',
      name: '项目管理',
      label: '项目管理',
      pinyin: '项目管理xiangmuguanli',
      children: [
        { value: 'projectlist.menu', name: '项目列表', label: '项目列表', pinyin: '项目列表xiangmuliebiao', children: null, disabled: false },
        { value: 'projectmember.menu', name: '成员管理', label: '成员管理', pinyin: '成员管理chengyuanguanli', children: null, disabled: false },
        {
          value: 'projectprogrestemp.menu',
          name: '项目进度模板',
          label: '项目进度模板',
          pinyin: '项目进度模板xiangmujindumoban',
          children: null,
          disabled: false,
        },
        { value: 'projectsettings.menu', name: '项目配置', label: '项目配置', pinyin: '项目配置xiangmupeizhi', children: null, disabled: false },
      ],
      disabled: false,
    },
    {
      value: 'sms.menu',
      name: '短信管理',
      label: '短信管理',
      pinyin: '短信管理duanxinguanli',
      children: [
        { value: 'smsmessage.menu', name: '发送记录', label: '发送记录', pinyin: '发送记录fasongjilu', children: null, disabled: false },
        { value: 'smstemplate.menu', name: '短信模板', label: '短信模板', pinyin: '短信模板duanxinmoban', children: null, disabled: false },
      ],
      disabled: false,
    },
    {
      value: 'system.menu',
      name: '系统管理',
      label: '系统管理',
      pinyin: '系统管理xitongguanli',
      children: [
        { value: 'systemdictionary.menu', name: '数据字典', label: '数据字典', pinyin: '数据字典shujuzidian', children: null, disabled: false },
        { value: 'systemoperatelog.menu', name: '操作记录', label: '操作记录', pinyin: '操作记录caozuojilu', children: null, disabled: false },
        { value: 'systemresource.menu', name: '权限资源', label: '权限资源', pinyin: '权限资源quanxianziyuan', children: null, disabled: false },
        { value: 'systemsystemconfig.menu', name: '系统配置', label: '系统配置', pinyin: '系统配置xitongpeizhi', children: null, disabled: false },
        { value: 'systemteammember.menu', name: '系统用户', label: '系统用户', pinyin: '系统用户xitongyonghu', children: null, disabled: false },
        { value: 'systemteamrole.menu', name: '系统角色', label: '系统角色', pinyin: '系统角色xitongjiaose', children: null, disabled: false },
      ],
      disabled: false,
    },
    { value: 'welcome.menu', name: 'welcome', label: 'welcome', pinyin: 'welcomewelcome', children: null, disabled: false },
  ],
  success: true,
  message: '操作成功',
  type: [
    { value: 'menu', name: '菜单资源', label: '菜单资源', pinyin: '菜单资源caidanziyuan', children: null, disabled: false },
    { value: 'app', name: '系统资源', label: '系统资源', pinyin: '系统资源xitongziyuan', children: null, disabled: false },
    { value: 'TABLE_COLUMN', name: '表格列信息', label: '表格列信息', pinyin: '表格列信息biaogeliexinxi', children: null, disabled: false },
    { value: 'DYNAMIC_DATA', name: '动态数据资源', label: '动态数据资源', pinyin: '动态数据资源dongtaishujuziyuan', children: null, disabled: false },
    { value: 'STATIC_DATA', name: '静态资源', label: '静态资源', pinyin: '静态资源jingtaiziyuan', children: null, disabled: false },
    { value: 'sensitive', name: '敏感资源', label: '敏感资源', pinyin: '敏感资源minganziyuan', children: null, disabled: false },
  ],
  treeData: [
    {
      value: 'clock.menu',
      name: '巡检管理',
      label: '巡检管理',
      pinyin: '巡检管理xunjianguanli',
      children: [
        { value: 'clockclockinspection.menu', name: '巡检记录', label: '巡检记录', pinyin: '巡检记录xunjianjilu', children: null, disabled: false },
        { value: 'clockfeedback.menu', name: '反馈列表', label: '反馈列表', pinyin: '反馈列表fankuiliebiao', children: null, disabled: false },
      ],
      disabled: false,
    },
    {
      value: 'comments.menu',
      name: '合作公司管理',
      label: '合作公司管理',
      pinyin: '合作公司管理hezuogongsiguanli',
      children: [
        { value: 'comment.menu', name: '评论记录', label: '评论记录', pinyin: '评论记录pinglunjilu', children: null, disabled: false },
        { value: 'commentoption.menu', name: '选项管理', label: '选项管理', pinyin: '选项管理xuanxiangguanli', children: null, disabled: false },
        { value: 'company.menu', name: '合作公司', label: '合作公司', pinyin: '合作公司hezuogongsi', children: null, disabled: false },
      ],
      disabled: false,
    },
    {
      value: 'content.menu',
      name: '内容管理',
      label: '内容管理',
      pinyin: '内容管理neirongguanli',
      children: [
        { value: 'catalog.menu', name: '目录', label: '目录', pinyin: '目录mulu', children: null, disabled: false },
        { value: 'contentposts.menu', name: '文章', label: '文章', pinyin: '文章wenzhang', children: null, disabled: false },
      ],
      disabled: false,
    },
    {
      value: 'project.menu',
      name: '项目管理',
      label: '项目管理',
      pinyin: '项目管理xiangmuguanli',
      children: [
        { value: 'projectlist.menu', name: '项目列表', label: '项目列表', pinyin: '项目列表xiangmuliebiao', children: null, disabled: false },
        { value: 'projectmember.menu', name: '成员管理', label: '成员管理', pinyin: '成员管理chengyuanguanli', children: null, disabled: false },
        {
          value: 'projectprogrestemp.menu',
          name: '项目进度模板',
          label: '项目进度模板',
          pinyin: '项目进度模板xiangmujindumoban',
          children: null,
          disabled: false,
        },
        { value: 'projectsettings.menu', name: '项目配置', label: '项目配置', pinyin: '项目配置xiangmupeizhi', children: null, disabled: false },
      ],
      disabled: false,
    },
    {
      value: 'sms.menu',
      name: '短信管理',
      label: '短信管理',
      pinyin: '短信管理duanxinguanli',
      children: [
        { value: 'smsmessage.menu', name: '发送记录', label: '发送记录', pinyin: '发送记录fasongjilu', children: null, disabled: false },
        { value: 'smstemplate.menu', name: '短信模板', label: '短信模板', pinyin: '短信模板duanxinmoban', children: null, disabled: false },
      ],
      disabled: false,
    },
    {
      value: 'system.menu',
      name: '系统管理',
      label: '系统管理',
      pinyin: '系统管理xitongguanli',
      children: [
        { value: 'systemdictionary.menu', name: '数据字典', label: '数据字典', pinyin: '数据字典shujuzidian', children: null, disabled: false },
        { value: 'systemoperatelog.menu', name: '操作记录', label: '操作记录', pinyin: '操作记录caozuojilu', children: null, disabled: false },
        { value: 'systemresource.menu', name: '权限资源', label: '权限资源', pinyin: '权限资源quanxianziyuan', children: null, disabled: false },
        { value: 'systemsystemconfig.menu', name: '系统配置', label: '系统配置', pinyin: '系统配置xitongpeizhi', children: null, disabled: false },
        { value: 'systemteammember.menu', name: '系统用户', label: '系统用户', pinyin: '系统用户xitongyonghu', children: null, disabled: false },
        { value: 'systemteamrole.menu', name: '系统角色', label: '系统角色', pinyin: '系统角色xitongjiaose', children: null, disabled: false },
      ],
      disabled: false,
    },
    { value: 'welcome.menu', name: 'welcome', label: 'welcome', pinyin: 'welcomewelcome', children: null, disabled: false },
  ],
};