one-boot.version: 1.0.0-SNAPSHOT

application: 
  url: 
  
# logging path
logging:
  path: ./logs
  level:
    com.codeaone.boot.sample.repository.mapper: debug
    com.codeaone.cloud.authbus.repository.mapper: debug
    com.codeaone.cloud.customer.repository.mapper: debug
    com.codeaone.oneboot.extend.schedule.repository.mapper: debug
    com.codeaone.bigtrade.repository.mapper: debug
    org.springframework.security: info 
    com.codeaone.project.repository.mapper: debug
    httpclient: info
    
static:
  file:
    localpath: D:/leibo/upload/static/
    http-path: http://127.0.0.1:8080/static/
    upload-path: D:/leibo/upload/

server:
  servlet:
    session:
      timeout: 43200 # session\u8d85\u65f6\u65f6\u95f4\u4e3a 12\u5c0f\u65f6
    context-path: 
  port: 8087
  compression:
    enabled: true
  tomcat:
    # tomcat\u7684URI\u7f16\u7801
    uri-encoding: UTF-8
    # tomcat\u6700\u5927\u7ebf\u7a0b\u6570\uff0c\u9ed8\u8ba4\u4e3a200
    max-threads: 20
    # Tomcat\u542f\u52a8\u521d\u59cb\u5316\u7684\u7ebf\u7a0b\u6570\uff0c\u9ed8\u8ba4\u503c25
    min-spare-threads: 10
    
# MyBatis Plus
mybatis-plus:
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  config-location: classpath:mybatis/config/mybatis-config.xml
  
spring:
  application:
    name: oneboot-pro
  activiti:
    # \u81ea\u52a8\u5efa\u8868
    database-schema: lbd
    database-schema-update: true
    history-level: full
    db-history-used: true
  # \u6a21\u677f\u5f15\u64ce
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # \u7981\u7528\u7f13\u5b58
    cache: false
  # \u6587\u4ef6\u4e0a\u4f20
  servlet:
     multipart:
       # \u5355\u4e2a\u6587\u4ef6\u5927\u5c0f
       max-file-size:  10MB
       # \u8bbe\u7f6e\u603b\u4e0a\u4f20\u7684\u6587\u4ef6\u5927\u5c0f
       max-request-size:  20MB
  # \u8d44\u6e90\u4fe1\u606f
  messages:
    # \u56fd\u9645\u5316\u8d44\u6e90\u6587\u4ef6\u8def\u5f84
    encoding: UTF-8
    basename: messages/messages_zh_CN
  ### \u6307\u5b9a\u7528\u4ec0\u4e48\u5b58\u50a8session\u4fe1\u606f redis
  session:
    store-type: none
  resources: 
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${static.file.localpath}
    
  ###\u672c\u5730\u73af\u5883\u4e0b\u4e0d\u914d\u7f6e\u4e5f\u53ef\u4ee5
  redis:
    host: 127.0.0.1
    port: 6379
    password: ssw0rd
    database: 0
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    #mysql\u7248\u672c\u4e3a8.0.13
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloudall?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai
    username: dev
    password: devQAZ13


nrsc:
  security:
    code:
      image:
        length: 6 #\u56fe\u5f62\u9a8c\u8bc1\u7801\u7684\u4f4d\u6570\u4e3a6\uff0c\u5c06\u8986\u76d6\u9ed8\u8ba4\u914d\u7f6e\u4e2d\u76844
        width: 100 #\u56fe\u5f62\u9a8c\u8bc1\u7801\u7684\u5bbd\u5ea6\u4e3a100\uff0c\u5c06\u8986\u76d6\u9ed8\u8ba4\u914d\u7f6e\u4e2d\u768467\uff0c\u4f46\u7531\u4e8e\u8bf7\u6c42\u4e2d\u8bbe\u7f6e\u7684\u5bbd\u5ea6\u4e3a200\uff0c\u6240\u4ee5\u771f\u6b63\u7684\u5bbd\u5ea6\u5c06\u4e3a200
        urls: /hello,/meinfo

    browser:
      #loginPage: /nrsc-login.html
      loginType: JSON
      #signUpUrl: /nrsc-signUp.html
      #signOutUrl: /nrsc-logout.html



security:
  oauth2:
    client:
      # \u771f\u5b9e\u9879\u76ee\u4e2d\u5e94\u653e\u5728\u6570\u636e\u5e93\u91cc
      client-id: nrsc
      client-secret: 123456
      # \u53ef\u4ee5\u5728\u8fd9\u91cc\u7b80\u5355\u7684\u6307\u5b9a\u4e00\u4e2a\u6216\u591a\u4e2aredirect-uri\uff0c\u4f46\u771f\u5b9e\u9879\u76ee\u4e2d\u4e0d\u4f1a\u8fd9\u6837\u505a\uff0c\u800c\u662f\u5c06\u5176\u653e\u5728\u6570\u636e\u5e93\u91cc
      # \u5927\u5bb6\u53ef\u4ee5\u597d\u597d\u60f3\u60f3\u4e3a\u4ec0\u4e48\u8d44\u6e90\u670d\u52a1\u5668\u975e\u8981\u6211\u4eec\u6307\u5b9aredirect-uri\u5462\uff1f
      registered-redirect-uri:
        - http://www.example.com
        - http://www.nrsc.com

activiti:
  db-history-used: true


